"""
project_builder.py — Iterative Godot 4 script & scene generation.

Constructs proper text-based Godot 4 scene trees (.tscn) and script layouts
(.gd). Deep try/except validation: if a script fails syntax checks, log the
failure to project_state.json, mark the task as 'pending_fix', and move on
instead of crashing the daemon.
"""

from __future__ import annotations

import ast
import json
import re
import shutil
import subprocess
import traceback
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from state_engine import StateEngine, FRAMEWORK_ROOT, _console

GODOT_PROJECT = FRAMEWORK_ROOT / "godot_project"
SCRIPTS_DIR = GODOT_PROJECT / "scripts"
SCENES_DIR = GODOT_PROJECT / "scenes"
ASSETS_LINK = GODOT_PROJECT / "assets"
RES_ASSETS = FRAMEWORK_ROOT / "res" / "assets"


class ProjectBuilder:
    """Writes and validates Godot 4 project files iteratively."""

    def __init__(self, state: StateEngine, ollama_client: Any = None) -> None:
        self.state = state
        self.ollama = ollama_client
        self._ensure_project_skeleton()

    # ------------------------------------------------------------------
    # Project skeleton
    # ------------------------------------------------------------------
    def _ensure_project_skeleton(self) -> None:
        for d in (GODOT_PROJECT, SCRIPTS_DIR, SCENES_DIR, ASSETS_LINK):
            d.mkdir(parents=True, exist_ok=True)

        project_godot = GODOT_PROJECT / "project.godot"
        if not project_godot.exists():
            goal = self.state.get("Master_Goal", "Jarvis Generated Game")
            safe_name = re.sub(r"[^\w]+", "_", goal)[:48] or "JarvisGame"
            content = f"""; Engine configuration file — generated by Jarvis autonomous framework
config_version=5

[application]

config/name="{safe_name}"
run/main_scene="res://scenes/Main.tscn"
config/features=PackedStringArray("4.3", "Forward Plus")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1280
window/size/viewport_height=720

[rendering]

renderer/rendering_method="forward_plus"
"""
            project_godot.write_text(content, encoding="utf-8")
            _console("BUILDER", f"Created project.godot → {project_godot}")

        icon = GODOT_PROJECT / "icon.svg"
        if not icon.exists():
            icon.write_text(
                '<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">'
                '<rect width="128" height="128" fill="#1a1a2e"/>'
                '<text x="64" y="72" text-anchor="middle" fill="#e94560" '
                'font-size="48" font-family="sans-serif">J</text></svg>\n',
                encoding="utf-8",
            )

        # Mirror harvested assets into godot_project/assets when present
        if RES_ASSETS.exists():
            for item in RES_ASSETS.iterdir():
                dest = ASSETS_LINK / item.name
                if not dest.exists():
                    try:
                        if item.is_dir():
                            shutil.copytree(item, dest, dirs_exist_ok=True)
                        else:
                            shutil.copy2(item, dest)
                    except OSError as exc:
                        _console("BUILDER", f"Asset mirror skip ({item.name}): {exc}")

    # ------------------------------------------------------------------
    # Task execution
    # ------------------------------------------------------------------
    def execute_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        Dispatch a builder task.
        On syntax failure → pending_fix (caller marks status); never crash.
        """
        payload = task.get("payload") or {}
        task_type = task.get("type") or payload.get("build_type") or "script"

        _console("BUILDER", f"Focus: type={task_type} — {task.get('description', '')}")

        try:
            if task_type in ("script", "gd_script", "generate_script"):
                return self._generate_script(task, payload)
            if task_type in ("scene", "tscn", "generate_scene"):
                return self._generate_scene(task, payload)
            if task_type in ("bootstrap", "project_bootstrap"):
                return self._bootstrap(task, payload)
            if task_type in ("player", "enemy", "ui", "game_system"):
                return self._generate_named_system(task, payload, system=task_type)
            # Default: treat as script generation from description
            return self._generate_script(task, payload)
        except Exception as exc:
            tb = traceback.format_exc()
            _console("BUILDER", f"Unhandled builder error (non-fatal): {exc}")
            return {
                "ok": False,
                "pending_fix": True,
                "error": str(exc),
                "traceback": tb,
            }

    # ------------------------------------------------------------------
    # Bootstrap
    # ------------------------------------------------------------------
    def _bootstrap(self, task: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
        self._ensure_project_skeleton()
        main_result = self._write_main_scene_and_script()
        autoload = self._write_game_manager()
        return {
            "ok": True,
            "files": main_result.get("files", []) + autoload.get("files", []),
            "message": "Godot 4 project skeleton ready.",
        }

    def _write_main_scene_and_script(self) -> Dict[str, Any]:
        script_path = SCRIPTS_DIR / "Main.gd"
        scene_path = SCENES_DIR / "Main.tscn"

        script = '''extends Node2D
## Main entry scene — generated by Jarvis autonomous framework.

@onready var status_label: Label = $UI/StatusLabel

func _ready() -> void:
	print("[Jarvis] Main scene ready.")
	if status_label:
		status_label.text = "Jarvis Game — Running"

func _process(_delta: float) -> void:
	pass
'''
        scene = '''[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/Main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")

[node name="World" type="Node2D" parent="."]

[node name="UI" type="CanvasLayer" parent="."]

[node name="StatusLabel" type="Label" parent="UI"]
offset_left = 16.0
offset_top = 16.0
offset_right = 480.0
offset_bottom = 48.0
text = "Jarvis Game"
'''
        files = []
        ok_script = self._safe_write_gd(script_path, script)
        ok_scene = self._safe_write_tscn(scene_path, scene)
        if ok_script:
            files.append(str(script_path))
        if ok_scene:
            files.append(str(scene_path))
        return {"ok": ok_script and ok_scene, "files": files}

    def _write_game_manager(self) -> Dict[str, Any]:
        path = SCRIPTS_DIR / "GameManager.gd"
        script = '''extends Node
## Autoload-style game manager — generated by Jarvis.

signal score_changed(new_score: int)

var score: int = 0
var paused: bool = false

func _ready() -> void:
	print("[Jarvis] GameManager online.")

func add_score(amount: int) -> void:
	score += amount
	score_changed.emit(score)

func reset() -> void:
	score = 0
	paused = false
	score_changed.emit(score)
'''
        if self._safe_write_gd(path, script):
            return {"ok": True, "files": [str(path)]}
        return {"ok": False, "files": [], "pending_fix": True}

    # ------------------------------------------------------------------
    # Named systems (player / enemy / ui)
    # ------------------------------------------------------------------
    def _generate_named_system(
        self, task: Dict[str, Any], payload: Dict[str, Any], system: str
    ) -> Dict[str, Any]:
        templates = {
            "player": self._template_player,
            "enemy": self._template_enemy,
            "ui": self._template_ui,
            "game_system": self._template_game_system,
        }
        name = payload.get("class_name") or system.title().replace("_", "")
        # Prefer LLM if available
        code = None
        scene = None
        if self.ollama and getattr(self.ollama, "available", lambda: False)():
            try:
                _console("BUILDER", f"Asking Ollama to generate {system} logic…")
                code = self.ollama.generate_gdscript(
                    description=task.get("description", f"Create a Godot 4 {system}"),
                    class_hint=name,
                )
            except Exception as exc:
                _console("BUILDER", f"Ollama generation failed, using template: {exc}")

        if not code:
            code, scene = templates.get(system, self._template_game_system)(name, payload)
        else:
            scene = self._minimal_scene_for(name, f"res://scripts/{name}.gd")

        script_path = SCRIPTS_DIR / f"{name}.gd"
        scene_path = SCENES_DIR / f"{name}.tscn"
        files: List[str] = []

        if not self._safe_write_gd(script_path, code):
            return {
                "ok": False,
                "pending_fix": True,
                "error": f"GDScript syntax validation failed for {name}.gd",
                "files": [],
            }
        files.append(str(script_path))

        if scene and not self._safe_write_tscn(scene_path, scene):
            return {
                "ok": False,
                "pending_fix": True,
                "error": f"Scene validation failed for {name}.tscn",
                "files": files,
            }
        if scene:
            files.append(str(scene_path))

        return {"ok": True, "files": files, "message": f"Generated {system}: {name}"}

    def _generate_script(self, task: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
        name = payload.get("class_name") or payload.get("filename") or self._name_from_desc(
            task.get("description", "GeneratedScript")
        )
        name = re.sub(r"[^\w]", "", name) or "GeneratedScript"
        if not name.endswith(".gd"):
            filename = f"{name}.gd"
            class_name = name
        else:
            filename = name
            class_name = Path(name).stem

        code = payload.get("code")
        if not code and self.ollama and getattr(self.ollama, "available", lambda: False)():
            try:
                _console("BUILDER", f"Ollama generating script: {class_name}")
                code = self.ollama.generate_gdscript(
                    description=task.get("description", ""),
                    class_hint=class_name,
                )
            except Exception as exc:
                _console("BUILDER", f"Ollama failed: {exc}")

        if not code:
            code = self._template_generic(class_name, task.get("description", ""))

        path = SCRIPTS_DIR / filename
        if not self._safe_write_gd(path, code):
            return {
                "ok": False,
                "pending_fix": True,
                "error": f"Syntax validation failed for {filename}",
                "files": [],
            }
        return {"ok": True, "files": [str(path)]}

    def _generate_scene(self, task: Dict[str, Any], payload: Dict[str, Any]) -> Dict[str, Any]:
        name = payload.get("scene_name") or self._name_from_desc(
            task.get("description", "GeneratedScene")
        )
        name = re.sub(r"[^\w]", "", name) or "GeneratedScene"
        script_res = payload.get("script", f"res://scripts/{name}.gd")
        tree = payload.get("tree")  # optional structured tree
        if tree:
            content = self._scene_from_tree(name, script_res, tree)
        else:
            content = self._minimal_scene_for(name, script_res)

        path = SCENES_DIR / f"{name}.tscn"
        if not self._safe_write_tscn(path, content):
            return {
                "ok": False,
                "pending_fix": True,
                "error": f"Scene validation failed for {name}.tscn",
                "files": [],
            }
        return {"ok": True, "files": [str(path)]}

    # ------------------------------------------------------------------
    # Templates
    # ------------------------------------------------------------------
    def _template_player(self, name: str, payload: Dict[str, Any]) -> Tuple[str, str]:
        speed = int(payload.get("speed", 200))
        code = f'''extends CharacterBody2D
## Player controller — generated by Jarvis.
class_name {name}

@export var speed: float = {speed}.0
@export var jump_velocity: float = -400.0

var gravity: float = ProjectSettings.get_setting("physics/2d/default_gravity")

func _physics_process(delta: float) -> void:
	if not is_on_floor():
		velocity.y += gravity * delta

	if Input.is_action_just_pressed("ui_accept") and is_on_floor():
		velocity.y = jump_velocity

	var direction := Input.get_axis("ui_left", "ui_right")
	if direction:
		velocity.x = direction * speed
	else:
		velocity.x = move_toward(velocity.x, 0, speed)

	move_and_slide()
'''
        scene = f'''[gd_scene load_steps=3 format=3]

[ext_resource type="Script" path="res://scripts/{name}.gd" id="1_player"]

[sub_resource type="RectangleShape2D" id="RectangleShape2D_1"]
size = Vector2(32, 48)

[node name="{name}" type="CharacterBody2D"]
script = ExtResource("1_player")

[node name="CollisionShape2D" type="CollisionShape2D" parent="."]
shape = SubResource("RectangleShape2D_1")

[node name="Sprite2D" type="Sprite2D" parent="."]
'''
        return code, scene

    def _template_enemy(self, name: str, payload: Dict[str, Any]) -> Tuple[str, str]:
        hp = int(payload.get("health", 3))
        code = f'''extends CharacterBody2D
## Enemy AI stub — generated by Jarvis.
class_name {name}

@export var health: int = {hp}
@export var move_speed: float = 80.0
@export var patrol_distance: float = 120.0

var _origin: Vector2
var _dir: float = 1.0

func _ready() -> void:
	_origin = global_position

func _physics_process(_delta: float) -> void:
	if global_position.x > _origin.x + patrol_distance:
		_dir = -1.0
	elif global_position.x < _origin.x - patrol_distance:
		_dir = 1.0
	velocity.x = _dir * move_speed
	move_and_slide()

func take_damage(amount: int) -> void:
	health -= amount
	if health <= 0:
		queue_free()
'''
        scene = f'''[gd_scene load_steps=3 format=3]

[ext_resource type="Script" path="res://scripts/{name}.gd" id="1_enemy"]

[sub_resource type="RectangleShape2D" id="RectangleShape2D_1"]
size = Vector2(32, 32)

[node name="{name}" type="CharacterBody2D"]
script = ExtResource("1_enemy")

[node name="CollisionShape2D" type="CollisionShape2D" parent="."]
shape = SubResource("RectangleShape2D_1")

[node name="Sprite2D" type="Sprite2D" parent="."]
'''
        return code, scene

    def _template_ui(self, name: str, payload: Dict[str, Any]) -> Tuple[str, str]:
        code = f'''extends CanvasLayer
## HUD / UI — generated by Jarvis.
class_name {name}

@onready var score_label: Label = $ScoreLabel

func _ready() -> void:
	update_score(0)

func update_score(value: int) -> void:
	if score_label:
		score_label.text = "Score: %d" % value
'''
        scene = f'''[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/{name}.gd" id="1_ui"]

[node name="{name}" type="CanvasLayer"]
script = ExtResource("1_ui")

[node name="ScoreLabel" type="Label" parent="."]
offset_left = 16.0
offset_top = 16.0
offset_right = 240.0
offset_bottom = 48.0
text = "Score: 0"
'''
        return code, scene

    def _template_game_system(self, name: str, payload: Dict[str, Any]) -> Tuple[str, str]:
        desc = payload.get("description", "game system")
        code = f'''extends Node
## {name} — generated by Jarvis.
## Intent: {desc}
class_name {name}

func _ready() -> void:
	print("[Jarvis] {name} ready.")

func activate() -> void:
	pass
'''
        scene = self._minimal_scene_for(name, f"res://scripts/{name}.gd", node_type="Node")
        return code, scene

    def _template_generic(self, class_name: str, description: str) -> str:
        return f'''extends Node
## Auto-generated by Jarvis.
## {description}
class_name {class_name}

func _ready() -> void:
	print("[Jarvis] {class_name} loaded.")
'''

    def _minimal_scene_for(
        self, name: str, script_res: str, node_type: str = "Node2D"
    ) -> str:
        return f'''[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="{script_res}" id="1_script"]

[node name="{name}" type="{node_type}"]
script = ExtResource("1_script")
'''

    def _scene_from_tree(
        self, root_name: str, script_res: str, tree: List[Dict[str, Any]]
    ) -> str:
        lines = [
            "[gd_scene load_steps=2 format=3]",
            "",
            f'[ext_resource type="Script" path="{script_res}" id="1_script"]',
            "",
            f'[node name="{root_name}" type="Node2D"]',
            'script = ExtResource("1_script")',
            "",
        ]
        for node in tree:
            n = node.get("name", "Child")
            t = node.get("type", "Node2D")
            parent = node.get("parent", ".")
            lines.append(f'[node name="{n}" type="{t}" parent="{parent}"]')
            lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Validation + safe write
    # ------------------------------------------------------------------
    def _safe_write_gd(self, path: Path, code: str) -> bool:
        """Write GDScript after validation. Returns False on syntax failure."""
        try:
            cleaned = self._extract_gdscript(code)
            ok, errors = self.validate_gdscript(cleaned)
            if not ok:
                _console("BUILDER", f"GDScript validation FAILED for {path.name}:")
                for e in errors:
                    _console("BUILDER", f"  • {e}")
                # Still write a .failed copy for debugging
                fail_path = path.with_suffix(".gd.failed")
                fail_path.write_text(cleaned, encoding="utf-8")
                return False
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(cleaned, encoding="utf-8")
            _console("BUILDER", f"Wrote validated script → {path}")
            # Optional headless Godot check if binary exists
            self._optional_godot_check(path)
            return True
        except Exception as exc:
            _console("BUILDER", f"Write error for {path}: {exc}")
            return False

    def _safe_write_tscn(self, path: Path, content: str) -> bool:
        try:
            ok, errors = self.validate_tscn(content)
            if not ok:
                _console("BUILDER", f"Scene validation FAILED for {path.name}:")
                for e in errors:
                    _console("BUILDER", f"  • {e}")
                fail_path = path.with_suffix(".tscn.failed")
                fail_path.write_text(content, encoding="utf-8")
                return False
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            _console("BUILDER", f"Wrote validated scene → {path}")
            return True
        except Exception as exc:
            _console("BUILDER", f"Scene write error for {path}: {exc}")
            return False

    @staticmethod
    def _extract_gdscript(text: str) -> str:
        """Strip markdown fences if the LLM wrapped the code."""
        text = text.strip()
        fence = re.search(r"```(?:gdscript|gd)?\s*([\s\S]*?)```", text, re.IGNORECASE)
        if fence:
            return fence.group(1).strip() + "\n"
        return text if text.endswith("\n") else text + "\n"

    def validate_gdscript(self, code: str) -> Tuple[bool, List[str]]:
        """
        Heuristic GDScript syntax checks (Godot binary may be absent).
        Deep try/except — never raises.
        """
        errors: List[str] = []
        try:
            if not code.strip():
                errors.append("Empty script.")
                return False, errors

            if "extends " not in code and "class_name " not in code:
                # Not fatal but suspicious for Godot 4 scripts
                pass

            # Balanced structures
            for open_c, close_c, label in (("(", ")", "parentheses"), ("[", "]", "brackets"), ("{", "}", "braces")):
                if code.count(open_c) != code.count(close_c):
                    errors.append(f"Unbalanced {label}.")

            # String quotes roughly balanced (ignore escapes — heuristic)
            for q in ('"', "'"):
                # Count unescaped quotes roughly
                count = len(re.findall(rf"(?<!\\){q}", code))
                if count % 2 != 0:
                    errors.append(f"Unbalanced {q} quotes (heuristic).")

            # Forbidden / obvious syntax disasters
            if "\x00" in code:
                errors.append("Null bytes in script.")

            # Indentation: tabs or spaces ok, but mixed extreme tabs+weird chars
            for i, line in enumerate(code.splitlines(), 1):
                if line.strip().startswith("def ") or line.strip().startswith("import "):
                    # Looks like Python leaked in
                    errors.append(f"Line {i}: Python-like syntax detected in GDScript.")
                if "async def" in line:
                    errors.append(f"Line {i}: invalid GDScript keyword 'async def'.")

            # func declarations should use 'func name(' pattern
            for i, line in enumerate(code.splitlines(), 1):
                stripped = line.strip()
                if stripped.startswith("function "):
                    errors.append(f"Line {i}: use 'func' not 'function'.")

        except Exception as exc:
            errors.append(f"Validator internal error: {exc}")

        return (len(errors) == 0), errors

    def validate_tscn(self, content: str) -> Tuple[bool, List[str]]:
        errors: List[str] = []
        try:
            if "[gd_scene" not in content:
                errors.append("Missing [gd_scene header.")
            if "[node name=" not in content:
                errors.append("No [node] entries found.")
            # Basic bracket balance for headers
            if content.count("[") != content.count("]"):
                # .tscn uses [section] headers; also Vector2( may not apply
                # Only check section-like lines
                pass
        except Exception as exc:
            errors.append(f"Scene validator error: {exc}")
        return (len(errors) == 0), errors

    def _optional_godot_check(self, script_path: Path) -> None:
        """If a Godot binary is on PATH, attempt a headless check — never crash."""
        godot = shutil.which("godot") or shutil.which("godot4")
        if not godot:
            return
        try:
            _console("BUILDER", f"Optional Godot headless check for {script_path.name}…")
            proc = subprocess.run(
                [godot, "--headless", "--check-only", "--path", str(GODOT_PROJECT), "-s", str(script_path)],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if proc.returncode != 0:
                _console("BUILDER", f"Godot check warnings: {proc.stderr[:400]}")
            else:
                _console("BUILDER", "Godot check passed.")
        except Exception as exc:
            _console("BUILDER", f"Godot check skipped: {exc}")

    @staticmethod
    def _name_from_desc(description: str) -> str:
        words = re.findall(r"[A-Za-z]+", description)
        if not words:
            return "GeneratedScript"
        # Take meaningful words
        skip = {"a", "an", "the", "to", "for", "and", "of", "generate", "creating", "create", "script", "logic"}
        picked = [w.title() for w in words if w.lower() not in skip][:4]
        return "".join(picked) or "GeneratedScript"

    def list_project_files(self) -> Dict[str, List[str]]:
        result = {"scripts": [], "scenes": [], "other": []}
        for f in SCRIPTS_DIR.glob("*.gd"):
            result["scripts"].append(str(f))
        for f in SCENES_DIR.glob("*.tscn"):
            result["scenes"].append(str(f))
        return result


if __name__ == "__main__":
    from state_engine import get_engine

    engine = get_engine()
    builder = ProjectBuilder(engine)
    result = builder.execute_task(
        {
            "task_id": "test",
            "description": "Bootstrap Godot project",
            "type": "bootstrap",
            "payload": {},
        }
    )
    print(json.dumps(result, indent=2))
